import React, { useState, useMemo, useEffect } from 'react';
import { useOutletContext } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import './AssetLibrary.css';

// Removed static filters

function AssetCard({ asset }) {
  const isArchived = asset.section === 'archived';
  return (
    <div className="asset-card" style={isArchived ? { opacity: 0.6 } : {}}>
      <div className="thumb" style={{ background: asset.thumbBg }}>
        <div className="preview-text" style={{ fontSize: asset.previewFontSize || undefined, color: asset.previewColor || undefined }}
          dangerouslySetInnerHTML={{ __html: asset.preview }} />
      </div>
      <div className="body">
        <div className="title">{asset.title}</div>
        <div className="meta-row">
          <span className={`agent-mini ${asset.agentLabel === 'SEO' ? 'agent-seo' : `agent-${asset.agent}`}`}>{asset.agentLabel}</span>
          {' '}{asset.agentName} &middot; {asset.time} &middot; <span className="ver">{asset.version}</span>
        </div>
      </div>
      <div className={`status-strip strip-${asset.status}`}>
        <span>{asset.statusText}</span><span>{asset.metric}</span>
      </div>
    </div>
  );
}

export default function AssetLibrary() {
  const { setSidebarOpen } = useOutletContext();
  const { workspace, activeProductId } = useAuth();
  const [activeFilter, setActiveFilter] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [dbAssets, setDbAssets] = useState([]);

  useEffect(() => {
    if (!workspace) return;
    const fetchAssets = async () => {
      try {
        const token = localStorage.getItem('nexus_token');
        let url = `/api/assets?workspaceId=${workspace.id}`;
        if (activeProductId) {
          url += `&productId=${activeProductId}`;
        }
        const res = await fetch(url, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        if (res.ok) {
          const data = await res.json();
          // Hydrate the DB records with rich UI properties for the prototype
          const hydrated = data.map(dbItem => {
            const agentMap = { smm: { label: 'S', name: 'SMM', bg: 'linear-gradient(135deg, #1e3a8a, #3b82f6)' }, bdm: { label: 'B', name: 'BDM', bg: 'linear-gradient(135deg, #14532d, #16a34a)' } };
            const ag = agentMap[dbItem.type] || { label: 'A', name: 'Agent', bg: 'linear-gradient(135deg, #404040, #525252)' };
            
            return {
              id: dbItem.id,
              title: dbItem.title,
              agent: dbItem.type,
              agentLabel: ag.label,
              agentName: ag.name,
              time: new Date(dbItem.createdAt).toLocaleDateString(),
              version: 'v1',
              status: dbItem.status,
              statusText: dbItem.status === 'live' ? '● Live' : dbItem.status === 'draft' ? '○ Draft' : '⨯ Archived',
              metric: '—',
              section: dbItem.status,
              thumbBg: ag.bg,
              preview: '<strong>' + dbItem.title + '</strong><br/><br/>Generated by Nexus CMO AI.'
            };
          });
          setDbAssets(hydrated);
        }
      } catch (err) {
        console.error(err);
      }
    };
    fetchAssets();
  }, [workspace, activeProductId]);

  const filtered = useMemo(() => {
    return dbAssets.filter(a => {
      if (activeFilter !== 'all' && a.agent !== activeFilter) return false;
      if (searchQuery && !a.title.toLowerCase().includes(searchQuery.toLowerCase())) return false;
      return true;
    });
  }, [activeFilter, searchQuery, dbAssets]);

  const dynamicFilters = useMemo(() => [
    { key: 'all', label: 'All', count: dbAssets.length },
    { key: 'bdm', label: 'BDM', count: dbAssets.filter(a => a.agent === 'bdm').length, avatarClass: 'agent-bdm', avatarLabel: 'B' },
    { key: 'smm', label: 'SMM', count: dbAssets.filter(a => a.agent === 'smm').length, avatarClass: 'agent-smm', avatarLabel: 'S' },
    { key: 'seo', label: 'SEO', count: dbAssets.filter(a => a.agent === 'seo').length, avatarClass: 'agent-seo', avatarLabel: 'SEO' },
    { key: 'design', label: 'Design', count: dbAssets.filter(a => a.agent === 'design').length, avatarClass: 'agent-design', avatarLabel: 'D' },
    { key: 'data', label: 'Data', count: dbAssets.filter(a => a.agent === 'data').length, avatarClass: 'agent-data', avatarLabel: 'DA' },
  ], [dbAssets]);

  const live = filtered.filter(a => a.section === 'live');
  const draft = filtered.filter(a => a.section === 'draft');
  const archived = filtered.filter(a => a.section === 'archived');

  return (
    <>
      <div className="topbar">
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <button className="hamburger" onClick={() => setSidebarOpen(true)}>☰</button>
          <div>
            <div className="crumb">Workspace › Asset Library</div>
            <div className="title">Asset Library</div>
          </div>
        </div>
        <div className="actions">
          <button className="btn btn-ghost btn-sm">↓ Export selected</button>
          <button className="btn btn-primary btn-sm">+ Upload asset</button>
        </div>
      </div>

      <div className="content">
        <div className="filter-bar">
          <input
            className="search"
            type="text"
            placeholder="🔍 Search assets…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          {dynamicFilters.map(f => (
            <span
              key={f.key}
              className={`chip${activeFilter === f.key ? ' active' : ''}`}
              onClick={() => setActiveFilter(f.key)}
            >
              {f.avatarClass && <span className={`agent-mini ${f.avatarClass}`}>{f.avatarLabel}</span>}
              {f.label} &middot; {f.count}
            </span>
          ))}
          <span style={{ flex: 1 }}></span>
          <select style={{ width: 'auto', padding: '6px 10px', fontSize: '12px', borderRadius: '6px', border: '1px solid var(--border-2)', background: 'var(--bg-1)', color: 'var(--text-1)' }}>
            <option>Latest first</option>
            <option>Oldest first</option>
            <option>Most used</option>
          </select>
        </div>

        {/* LIVE / ACTIVE */}
        {live.length > 0 && (
          <>
            <div className="section-h">
              <h3>🟢 Live &amp; in use</h3>
              <div className="meta">{live.length} assets</div>
            </div>
            <div className="asset-grid">
              {live.map(a => <AssetCard key={a.id} asset={a} />)}
            </div>
          </>
        )}

        {/* DRAFTS */}
        {draft.length > 0 && (
          <>
            <div className="section-h">
              <h3>🟡 Drafts waiting for review</h3>
              <div className="meta">{draft.length} assets &middot; need your sign-off</div>
            </div>
            <div className="asset-grid">
              {draft.map(a => <AssetCard key={a.id} asset={a} />)}
            </div>
          </>
        )}

        {/* ARCHIVED */}
        {archived.length > 0 && (
          <>
            <div className="section-h">
              <h3>📦 Archived &amp; superseded</h3>
              <div className="meta">{archived.length} older versions</div>
            </div>
            <div className="asset-grid">
              {archived.map(a => <AssetCard key={a.id} asset={a} />)}
            </div>
          </>
        )}

        {live.length === 0 && draft.length === 0 && archived.length === 0 && (
          <div style={{ textAlign: 'center', padding: '60px 20px', color: 'var(--text-3)' }}>
            <div style={{ fontSize: '36px', marginBottom: '12px' }}>🔍</div>
            <div style={{ fontSize: '16px', fontWeight: 600 }}>No assets match your filter</div>
            <div style={{ fontSize: '13px', marginTop: '4px' }}>Try a different agent or clear the search.</div>
          </div>
        )}
      </div>
    </>
  );
}
